//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Leagues = new HashSet<League>();
            this.Teams = new HashSet<Team>();
            this.Leagues1 = new HashSet<League>();
        }
    
        public System.Guid UserId { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public bool IsAdmin { get; set; }
        public bool ReceiveEmails { get; set; }
    
        public virtual ICollection<League> Leagues { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<League> Leagues1 { get; set; }
    }
}
